global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']  # For Docker Desktop
    metrics_path: /actuator/prometheus
    scheme: http
    
    # Add these labels to all metrics from this job
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'samjhadoo-backend'
