package com.samjhadoo.model.enums;

public enum NotificationType {
    SESSION_REMINDER,
    SESSION_CONFIRMED,
    SESSION_CANCELLED,
    BOOKING_REQUEST,
    BOOKING_CONFIRMED,
    PAYMENT_RECEIVED,
    PAYMENT_REFUNDED,
    REVIEW_POSTED,
    REVIEW_APPROVED,
    REVIEW_REJECTED,
    COMMUNITY_JOINED,
    COMMUNITY_MEMBER_JOINED,
    COMMUNITY_CREATED,
    MESSAGE_RECEIVED,
    MENTOR_APPROVED,
    ACCOUNT_SUSPENDED,
    GENERAL
}
